export const CHANGE_BASE_CURRENCY = "CHANGE_BASE_CURRENCY";
export const CHANGE_TERMS_CURRENCY = "CHANGE_TERMS_CURRENCY";
export const INPUT_CURRENCY_VALUE = "INPUT_CURRENCY_VALUE";
export const CONVERT_CURRENCY = "CONVERT_CURRENCY";
